In [1]:
!pip install matchbook

Collecting matchbook
  Downloading matchbook-0.0.7.tar.gz (16 kB)
Collecting requests==2.13.0
  Downloading requests-2.13.0-py2.py3-none-any.whl (584 kB)
Collecting python-dateutil==2.6.0
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194 kB)
Collecting pytz==2017.2
  Downloading pytz-2017.2-py2.py3-none-any.whl (484 kB)
Requirement already satisfied: six>=1.5 in c:\users\dell5520\pycharmprojects\personal\venv\lib\site-packages (from python-dateutil==2.6.0->matchbook) (1.16.0)
Building wheels for collected packages: matchbook
  Building wheel for matchbook (setup.py): started
  Building wheel for matchbook (setup.py): finished with status 'done'
  Created wheel for matchbook: filename=matchbook-0.0.7-py3-none-any.whl size=25529 sha256=44c44c083fba2e0baa9d89d750a4e173afe6bbee0cc52f69b8868823a79254df
  Stored in directory: c:\users\dell5520\appdata\local\pip\cache\wheels\95\ff\be\3c0d9397122e080986e092633c375339ab7b8fdaf61d12a4e6
Successfully built matchbook
Installing collected packages: requests, pytz, python-dateutil, matchbook
  Attempting uninstall: requests
    Found existing installation: requests 2.28.0
    Uninstalling requests-2.28.0:
      Successfully uninstalled requests-2.28.0
  Attempting uninstall: pytz
    Found existing installation: pytz 2022.7
    Uninstalling pytz-2022.7:
      Successfully uninstalled pytz-2022.7
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.2
    Uninstalling python-dateutil-2.8.2:
      Successfully uninstalled python-dateutil-2.8.2
Successfully installed matchbook-0.0.7 python-dateutil-2.6.0 pytz-2017.2 requests-2.13.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yfinance 0.2.3 requires pytz>=2022.5, but you have pytz 2017.2 which is incompatible.
yfinance 0.2.3 requires requests>=2.26, but you have requests 2.13.0 which is incompatible.
tweepy 4.12.1 requires requests<3,>=2.27.0, but you have requests 2.13.0 which is incompatible.
tensorboard 2.9.0 requires requests<3,>=2.21.0, but you have requests 2.13.0 which is incompatible.
streamlit 1.27.2 requires python-dateutil<3,>=2.7.3, but you have python-dateutil 2.6.0 which is incompatible.
streamlit 1.27.2 requires requests<3,>=2.27, but you have requests 2.13.0 which is incompatible.
pandas 1.4.2 requires python-dateutil>=2.8.1, but you have python-dateutil 2.6.0 which is incompatible.
pandas 1.4.2 requires pytz>=2020.1, but you have pytz 2017.2 which is incompatible.
mlflow 1.26.1 requires requests>=2.17.3, but you have requests 2.13.0 which is incompatible.
matplotlib 3.5.2 requires python-dateutil>=2.7, but you have python-dateutil 2.6.0 which is incompatible.
jupyter-client 7.3.4 requires python-dateutil>=2.8.2, but you have python-dateutil 2.6.0 which is incompatible.
docker 5.0.3 requires requests!=2.18.0,>=2.14.2, but you have requests 2.13.0 which is incompatible.
databricks-cli 0.16.7 requires requests>=2.17.3, but you have requests 2.13.0 which is incompatible.
ccxt 2.5.33 requires requests>=2.18.4, but you have requests 2.13.0 which is incompatible.
WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'C:\Users\Dell5520\PycharmProjects\personal\venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [2]:
import os
from matchbook import APIClient
from matchbook.enums import Side

In [3]:
mb = APIClient('adbushnell', 'palebroccoliwin123$')
mb.login()

In [4]:
sports = mb.reference_data.get_sports()

RuntimeError: dictionary keys changed during iteration

In [11]:
# lets go in raw!

# following from here: https://developers.matchbook.com/reference/login

# login
import requests
import json
import pandas as pd

url = "https://api.matchbook.com/bpapi/rest/security/session"
payload ={
    "username":'adbushnell',
    "password":'palebroccoliwin123$'
    }

header = {
    'content-type': 'application/json;charset=UTF-8',
    'accept': '*/*'
}
def login():
    r = requests.post(url, data=json.dumps(payload), headers=header)
    data = r.json()
    return data['session-token']


token = login()
print(token)

681420_fd6b6c96b3e6dfedf0e82de77454c923

In [7]:
# logout
# tested this with an old token
url = "https://api.matchbook.com/bpapi/rest/security/session"

headers = {
    "accept": "application/json",
    'session-token': '681420_ce3c8f61546f30cc5e2fcf7d36df8780'
    #"User-Agent": "api-doc-test-client"
}

response = requests.delete(url, headers=headers)

print(response.text)

{"session-token":"681420_ce3c8f61546f30cc5e2fcf7d36df8780","user-id":681420,"username":"adbushnell"}

In [8]:
response

In [12]:
# check session is active
url = "https://api.matchbook.com/bpapi/rest/security/session"

headers = {
    "accept": "application/json",
    'session-token': '681420_fd6b6c96b3e6dfedf0e82de77454c923'
}

response = requests.get(url, headers=headers)
print(response.text)

{"session-token":"681420_fd6b6c96b3e6dfedf0e82de77454c923","user-id":681420}

In [13]:
response

In [14]:
# account info
url = "https://api.matchbook.com/edge/rest/account"

headers = {
    "accept": "application/json",
    'session-token': '681420_fd6b6c96b3e6dfedf0e82de77454c923'
}

response = requests.get(url, headers=headers)

print(response.text)

{"id":651418,"user-id":681420,"username":"adbushnell","status":"ACTIVE","commission-type":"VOLUME","currency":"GBP","country":"GB","balance":0.0,"exposure":0.0,"commission-reserve":0.0,"free-funds":0.0,"exclude-casino":false,"language":"en","exchange-type":"back-lay","odds-type":"DECIMAL","show-bet-confirmation":false,"show-position":true,"show-odds-rounding-message":true,"bet-slip-pinned":true,"given-names":"Alex","family-names":"Bushnell","email":"ad.bushnell@outlook.com","date-of-birth":"1998-04-04","roles":["USER"]}

In [15]:
# account balance
url = "https://api.matchbook.com/edge/rest/account/balance"

headers = {
    "accept": "application/json",
    'session-token': '681420_fd6b6c96b3e6dfedf0e82de77454c923'
}

response = requests.get(url, headers=headers)
print(response.text)

{"id":651418,"balance":0.0,"exposure":0.0,"commission-reserve":0.0,"free-funds":0.0,"bonus-free-funds":0.0}

In [16]:
# get sports
url = "https://api.matchbook.com/edge/rest/lookups/sports?offset=0&per-page=20&order=name%20asc&status=active"

headers = {
    "accept": "application/json",
    'session-token': '681420_fd6b6c96b3e6dfedf0e82de77454c923'
}

response = requests.get(url, headers=headers)
print(response.text)

{"total":48,"per-page":20,"offset":0,"sports":[{"name":"American Football","id":1,"type":"SPORT","url-name":"american-football"},{"name":"Athletics","id":555636871580009,"type":"SPORT","url-name":"athletics"},{"name":"Australian Rules","id":112,"type":"SPORT","url-name":"australian-rules"},{"name":"Auto Racing","id":13,"type":"SPORT","url-name":"auto-racing"},{"name":"Baseball","id":3,"type":"SPORT","url-name":"baseball"},{"name":"Basketball","id":4,"type":"SPORT","url-name":"basketball"},{"name":"Boxing","id":14,"type":"SPORT","url-name":"boxing"},{"name":"Chess","id":1387652895550017,"type":"SPORT","url-name":"chess"},{"name":"Cricket","id":110,"type":"SPORT","url-name":"cricket"},{"name":"Current Events","id":11,"type":"SPORT","url-name":"current-events"},{"name":"Cycling","id":115,"type":"SPORT","url-name":"cycling"},{"name":"Darts","id":116,"type":"SPORT","url-name":"darts"},{"name":"E Specials","id":2365767644720008,"type":"SPORT","url-name":"e-specials"},{"name":"Enhanced Specials","id":1532612887820003,"type":"SPORT","url-name":"enhanced-specials"},{"name":"Eurovision 2022","id":2061617389960016,"type":"SPORT","url-name":"eurovision-2022"},{"name":"Eurovision 2023","id":2371634230370008,"type":"SPORT","url-name":"eurovision-2023"},{"name":"Formula 1","id":29471135545400054,"type":"SPORT","url-name":"formula-1"},{"name":"Gaelic Football","id":117,"type":"SPORT","url-name":"gaelic-football"},{"name":"Golf","id":8,"type":"SPORT","url-name":"golf"},{"name":"Greyhound Racing","id":241798357140019,"type":"SPORT","url-name":"greyhound-racing"}]}

In [17]:
# get events
url = "https://api.matchbook.com/edge/rest/events?offset=0&per-page=20&states=open%2Csuspended%2Cclosed%2Cgraded&exchange-type=back-lay&odds-type=DECIMAL&include-prices=false&price-depth=3&price-mode=expanded&include-event-participants=false&exclude-mirrored-prices=false"

headers = {
    "accept": "application/json",
    'session-token': '681420_fd6b6c96b3e6dfedf0e82de77454c923'
}

response = requests.get(url, headers=headers)
print(response.text)

{"offset":0,"per-page":20,"total":886,"events":[{"id":27457638747900078,"name":"UK - Next Labour Leader","sport-id":385227477790005,"start":"2025-01-01T07:00:00.000Z","in-running-flag":false,"allow-live-betting":false,"category-id":[385227477790005,1302896445450017,1529052331600003],"status":"closed","volume":0.0,"markets":[],"meta-tags":[{"id":385227477790005,"name":"Politics","type":"SPORT","url-name":"politics"},{"id":1302896445450017,"name":"Next Labour Leader","type":"COMPETITION","url-name":"next-labour-leader"},{"id":1529052331600003,"name":"UK Politics","type":"COMPETITION","url-name":"uk-politics"}]},{"id":29765170060200076,"name":"Any Player To Acheive Two Or More 147's Across All 4 Major Tournaments (Saudi, UK, Masters, World) (Max Payout\u00A03\u00A0Players)","sport-id":120,"start":"2025-04-02T08:59:00.000Z","in-running-flag":false,"allow-live-betting":false,"category-id":[120,292022482330036,400798618290009],"status":"closed","volume":257383.78794,"markets":[],"meta-tags":[{"id":120,"name":"Snooker","type":"SPORT","url-name":"snooker"},{"id":292022482330036,"name":"Block Trade","type":"OTHER","url-name":"block-trade"},{"id":400798618290009,"name":"World","type":"COUNTRY","url-name":"world"}]},{"id":31293426439100061,"name":"test","sport-id":8,"start":"2025-09-27T17:10:00.000Z","in-running-flag":false,"allow-live-betting":true,"category-id":[8,1862791962990016,30631793272600054,31293382129200047],"status":"closed","volume":0.0,"markets":[],"meta-tags":[{"id":8,"name":"Golf","type":"SPORT","url-name":"golf"},{"id":1862791962990016,"name":"Ryder Cup","type":"COMPETITION","url-name":"ryder-cup"},{"id":30631793272600054,"name":"September 27th 2025","type":"DATE","url-name":"september-27th-2025"},{"id":31293382129200047,"name":"Day 2 Foursomes Correct Score","type":"OTHER","url-name":"day-2-foursomes-correct-score"}]},{"id":31321268331600061,"name":"Next Labour Deputy Leader","sport-id":385227477790005,"start":"2025-10-07T17:00:00.000Z","in-running-flag":false,"allow-live-betting":false,"category-id":[385227477790005],"status":"closed","volume":161404.95404,"markets":[],"meta-tags":[{"id":385227477790005,"name":"Politics","type":"SPORT","url-name":"politics"}]},{"id":31380678522200061,"name":"2025 Buick LPGA Shanghai","sport-id":8,"start":"2025-10-12T23:59:00.000Z","in-running-flag":false,"allow-live-betting":false,"category-id":[8,423407498380010,28233032556300084,30119347090800038],"status":"closed","volume":0.0,"markets":[],"meta-tags":[{"id":8,"name":"Golf","type":"SPORT","url-name":"golf"},{"id":423407498380010,"name":"China","type":"COUNTRY","url-name":"china"},{"id":28233032556300084,"name":"Buick LPGA Shanghai","type":"COMPETITION","url-name":"buick-lpga-shanghai"},{"id":30119347090800038,"name":"October 12th 2025","type":"DATE","url-name":"october-12th-2025"}]},{"id":31380678358100061,"name":"2025 SAS Championship","sport-id":8,"start":"2025-10-12T23:59:00.000Z","in-running-flag":false,"allow-live-betting":false,"category-id":[8,1904152202480016,28234894100700084,30119347090800038],"status":"closed","volume":0.0,"markets":[],"meta-tags":[{"id":8,"name":"Golf","type":"SPORT","url-name":"golf"},{"id":1904152202480016,"name":"United States of America","type":"COUNTRY","url-name":"united-states-of-america"},{"id":28234894100700084,"name":"SAS Championship","type":"COMPETITION","url-name":"sas-championship"},{"id":30119347090800038,"name":"October 12th 2025","type":"DATE","url-name":"october-12th-2025"}]},{"id":31440780971800058,"name":"DP World India Championship 2025 ","sport-id":8,"start":"2025-10-16T01:05:00.000Z","in-running-flag":true,"allow-live-betting":true,"category-id":[8,410468520880009,489003593880009,645571519460013,30119351674200038,31440780969700047],"status":"open","volume":2357558.92154,"markets":[{"live":true,"event-id":31440780971800058,"id":31440783308500058,"name":"Winner","product":"EXCHANGE","start":"2025-10-16T01:05:00.000Z","status":"open","market-type":"outright","type":"multirunner","in-running-flag":true,"allow-live-betting":true,"volume":2321958.5392,"back-overround":149.59126,"number-of-winners":1,"runners":[{"withdrawn":false,"prices":[{"available-amount":79.00000,"currency":"GBP","odds-type":"DECIMAL","odds":7.00000,"decimal-odds":7.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":24.00000,"currency":"GBP","odds-type":"DECIMAL","odds":5.60000,"decimal-odds":5.60000,"side":"back","exchange-type":"back-lay"},{"available-amount":27.00000,"currency":"GBP","odds-type":"DECIMAL","odds":5.40000,"decimal-odds":5.40000,"side":"back","exchange-type":"back-lay"},{"available-amount":37.01033,"currency":"GBP","odds-type":"DECIMAL","odds":13.50000,"decimal-odds":13.50000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00074,"currency":"GBP","odds-type":"DECIMAL","odds":21.00000,"decimal-odds":21.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":30.00000,"decimal-odds":30.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:15:03.121Z","event-id":31440780971800058,"id":31440783311601058,"market-id":31440783308500058,"name":"Tommy Fleetwood","status":"open","volume":36422.63003,"event-participant-id":31440780981101058},{"withdrawn":false,"prices":[{"available-amount":4.00074,"currency":"GBP","odds-type":"DECIMAL","odds":8.40000,"decimal-odds":8.40000,"side":"back","exchange-type":"back-lay"},{"available-amount":12.00223,"currency":"GBP","odds-type":"DECIMAL","odds":8.20000,"decimal-odds":8.20000,"side":"back","exchange-type":"back-lay"},{"available-amount":17.00317,"currency":"GBP","odds-type":"DECIMAL","odds":8.00000,"decimal-odds":8.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":11.00204,"currency":"GBP","odds-type":"DECIMAL","odds":8.80000,"decimal-odds":8.80000,"side":"lay","exchange-type":"back-lay"},{"available-amount":16.00298,"currency":"GBP","odds-type":"DECIMAL","odds":9.00000,"decimal-odds":9.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":13.00242,"currency":"GBP","odds-type":"DECIMAL","odds":10.50000,"decimal-odds":10.50000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T10:41:43.846Z","event-id":31440780971800058,"id":31440783311401058,"market-id":31440783308500058,"name":"Rory McIlroy","status":"open","volume":37935.26538,"event-participant-id":31440780981000058},{"withdrawn":false,"prices":[{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":10.00000,"decimal-odds":10.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":9.80000,"decimal-odds":9.80000,"side":"back","exchange-type":"back-lay"},{"available-amount":24.00447,"currency":"GBP","odds-type":"DECIMAL","odds":9.40000,"decimal-odds":9.40000,"side":"back","exchange-type":"back-lay"},{"available-amount":21.00391,"currency":"GBP","odds-type":"DECIMAL","odds":11.00000,"decimal-odds":11.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":15.00279,"currency":"GBP","odds-type":"DECIMAL","odds":16.00000,"decimal-odds":16.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":65.00000,"decimal-odds":65.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:11:32.282Z","event-id":31440780971800058,"id":31440783309101058,"market-id":31440783308500058,"name":"Keita Nakajima","status":"open","volume":138787.26084,"event-participant-id":31440780979000058},{"withdrawn":false,"prices":[{"available-amount":48.00000,"currency":"GBP","odds-type":"DECIMAL","odds":15.00000,"decimal-odds":15.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":18.00000,"currency":"GBP","odds-type":"DECIMAL","odds":13.00000,"decimal-odds":13.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":51.00000,"currency":"GBP","odds-type":"DECIMAL","odds":10.00000,"decimal-odds":10.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":6.00112,"currency":"GBP","odds-type":"DECIMAL","odds":20.00000,"decimal-odds":20.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":38.01061,"currency":"GBP","odds-type":"DECIMAL","odds":24.00000,"decimal-odds":24.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":6.00112,"currency":"GBP","odds-type":"DECIMAL","odds":29.00000,"decimal-odds":29.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:10:39.536Z","event-id":31440780971800058,"id":31440783309501058,"market-id":31440783308500058,"name":"Brian Harman","status":"open","volume":18507.99259,"event-participant-id":31440780979500058},{"withdrawn":false,"prices":[{"available-amount":16.00298,"currency":"GBP","odds-type":"DECIMAL","odds":9.40000,"decimal-odds":9.40000,"side":"back","exchange-type":"back-lay"},{"available-amount":58.01080,"currency":"GBP","odds-type":"DECIMAL","odds":9.20000,"decimal-odds":9.20000,"side":"back","exchange-type":"back-lay"},{"available-amount":31.00000,"currency":"GBP","odds-type":"DECIMAL","odds":8.20000,"decimal-odds":8.20000,"side":"back","exchange-type":"back-lay"},{"available-amount":5.00093,"currency":"GBP","odds-type":"DECIMAL","odds":11.00000,"decimal-odds":11.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":34.00633,"currency":"GBP","odds-type":"DECIMAL","odds":11.50000,"decimal-odds":11.50000,"side":"lay","exchange-type":"back-lay"},{"available-amount":15.00279,"currency":"GBP","odds-type":"DECIMAL","odds":16.00000,"decimal-odds":16.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:12:18.522Z","event-id":31440780971800058,"id":31440783309301058,"market-id":31440783308500058,"name":"Ben Griffin","status":"open","volume":16295.71443,"event-participant-id":31440780979202058},{"withdrawn":false,"prices":[{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":28.00000,"decimal-odds":28.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":7.00130,"currency":"GBP","odds-type":"DECIMAL","odds":26.00000,"decimal-odds":26.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99336,"currency":"GBP","odds-type":"DECIMAL","odds":25.00000,"decimal-odds":25.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.00111,"currency":"GBP","odds-type":"DECIMAL","odds":32.00000,"decimal-odds":32.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":10.98647,"currency":"GBP","odds-type":"DECIMAL","odds":34.00000,"decimal-odds":34.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":5.99492,"currency":"GBP","odds-type":"DECIMAL","odds":40.00000,"decimal-odds":40.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:08:50.588Z","event-id":31440780971800058,"id":31440783312100058,"market-id":31440783308500058,"name":"Viktor Hovland","status":"open","volume":40510.43811,"event-participant-id":31440780981401058},{"withdrawn":false,"prices":[{"available-amount":38.00000,"currency":"GBP","odds-type":"DECIMAL","odds":5.00000,"decimal-odds":5.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":31.00000,"currency":"GBP","odds-type":"DECIMAL","odds":4.80000,"decimal-odds":4.80000,"side":"back","exchange-type":"back-lay"},{"available-amount":9.00000,"currency":"GBP","odds-type":"DECIMAL","odds":4.70000,"decimal-odds":4.70000,"side":"back","exchange-type":"back-lay"},{"available-amount":5.00093,"currency":"GBP","odds-type":"DECIMAL","odds":6.20000,"decimal-odds":6.20000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":8.00000,"decimal-odds":8.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":15.00000,"decimal-odds":15.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:14:19.046Z","event-id":31440780971800058,"id":31440783311900058,"market-id":31440783308500058,"name":"Shane Lowry","status":"open","volume":15935.33574,"event-participant-id":31440780981201058},{"withdrawn":false,"prices":[{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":130.00000,"decimal-odds":130.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":120.00000,"decimal-odds":120.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99596,"currency":"GBP","odds-type":"DECIMAL","odds":110.00000,"decimal-odds":110.00000,"side":"back","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:02:30.134Z","event-id":31440780971800058,"id":31440783309701058,"market-id":31440783308500058,"name":"Angel Ayora","status":"open","volume":21867.86556,"event-participant-id":31440780979601058},{"withdrawn":false,"prices":[{"available-amount":33.96560,"currency":"GBP","odds-type":"DECIMAL","odds":32.00000,"decimal-odds":32.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":7.00000,"currency":"GBP","odds-type":"DECIMAL","odds":30.00000,"decimal-odds":30.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":50.00931,"currency":"GBP","odds-type":"DECIMAL","odds":28.00000,"decimal-odds":28.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":7.99191,"currency":"GBP","odds-type":"DECIMAL","odds":80.00000,"decimal-odds":80.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":8.00223,"currency":"GBP","odds-type":"DECIMAL","odds":110.00000,"decimal-odds":110.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00111,"currency":"GBP","odds-type":"DECIMAL","odds":350.00000,"decimal-odds":350.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:10:39.027Z","event-id":31440780971800058,"id":31440783322300058,"market-id":31440783308500058,"name":"Jorge Campillo","status":"open","volume":22588.26514,"event-participant-id":31440780985301058},{"withdrawn":false,"prices":[{"available-amount":3.00084,"currency":"GBP","odds-type":"DECIMAL","odds":75.00000,"decimal-odds":75.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":1.99668,"currency":"GBP","odds-type":"DECIMAL","odds":70.00000,"decimal-odds":70.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":13.00242,"currency":"GBP","odds-type":"DECIMAL","odds":55.00000,"decimal-odds":55.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99563,"currency":"GBP","odds-type":"DECIMAL","odds":180.00000,"decimal-odds":180.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T10:52:59.969Z","event-id":31440780971800058,"id":31440783328201058,"market-id":31440783308500058,"name":"Jordan Smith","status":"open","volume":30419.54719,"event-participant-id":31440780989901058},{"withdrawn":false,"prices":[{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":46.00000,"decimal-odds":46.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":13.00242,"currency":"GBP","odds-type":"DECIMAL","odds":44.00000,"decimal-odds":44.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":16.00298,"currency":"GBP","odds-type":"DECIMAL","odds":40.00000,"decimal-odds":40.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99631,"currency":"GBP","odds-type":"DECIMAL","odds":55.00000,"decimal-odds":55.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":13.97678,"currency":"GBP","odds-type":"DECIMAL","odds":60.00000,"decimal-odds":60.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":5.00093,"currency":"GBP","odds-type":"DECIMAL","odds":65.00000,"decimal-odds":65.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:07:39.095Z","event-id":31440780971800058,"id":31440783331100058,"market-id":31440783308500058,"name":"Jayden Trey Schaper","status":"open","volume":28138.69268,"event-participant-id":31440780992000058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":200.00000,"decimal-odds":200.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":170.00000,"decimal-odds":170.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":85.00000,"decimal-odds":85.00000,"side":"back","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:14:29.660Z","event-id":31440780971800058,"id":31440783308900058,"market-id":31440783308500058,"name":"John Parry","status":"open","volume":22577.87945,"event-participant-id":31440780978600058},{"withdrawn":false,"prices":[{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":25.00000,"decimal-odds":25.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":8.99090,"currency":"GBP","odds-type":"DECIMAL","odds":24.00000,"decimal-odds":24.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":8.00000,"currency":"GBP","odds-type":"DECIMAL","odds":22.00000,"decimal-odds":22.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00056,"currency":"GBP","odds-type":"DECIMAL","odds":28.00000,"decimal-odds":28.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":10.98175,"currency":"GBP","odds-type":"DECIMAL","odds":29.00000,"decimal-odds":29.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":5.00000,"currency":"GBP","odds-type":"DECIMAL","odds":30.00000,"decimal-odds":30.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:07:00.171Z","event-id":31440780971800058,"id":31440783312300058,"market-id":31440783308500058,"name":"Michael Kim","status":"open","volume":21390.46264,"event-participant-id":31440780981600058},{"withdrawn":false,"prices":[{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":100.00000,"decimal-odds":100.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":1.99798,"currency":"GBP","odds-type":"DECIMAL","odds":95.00000,"decimal-odds":95.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.00074,"currency":"GBP","odds-type":"DECIMAL","odds":80.00000,"decimal-odds":80.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99746,"currency":"GBP","odds-type":"DECIMAL","odds":330.00000,"decimal-odds":330.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T10:52:20.437Z","event-id":31440780971800058,"id":31440783329801058,"market-id":31440783308500058,"name":"Andy Sullivan","status":"open","volume":17058.74453,"event-participant-id":31440780991101058},{"withdrawn":false,"prices":[{"available-amount":3.00056,"currency":"GBP","odds-type":"DECIMAL","odds":65.00000,"decimal-odds":65.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":60.00000,"decimal-odds":60.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":20.00372,"currency":"GBP","odds-type":"DECIMAL","odds":46.00000,"decimal-odds":46.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":120.00000,"decimal-odds":120.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":12.00335,"currency":"GBP","odds-type":"DECIMAL","odds":140.00000,"decimal-odds":140.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":5.99393,"currency":"GBP","odds-type":"DECIMAL","odds":150.00000,"decimal-odds":150.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:00:21.079Z","event-id":31440780971800058,"id":31440783312901058,"market-id":31440783308500058,"name":"Adrien Saddier","status":"open","volume":26905.54207,"event-participant-

In [21]:
events_json = response.json()
len(events_json)

4

In [22]:
events_json

{'offset': 0,
 'per-page': 20,
 'total': 886,
 'events': [{'id': 27457638747900078,
   'name': 'UK - Next Labour Leader',
   'sport-id': 385227477790005,
   'start': '2025-01-01T07:00:00.000Z',
   'in-running-flag': False,
   'allow-live-betting': False,
   'category-id': [385227477790005, 1302896445450017, 1529052331600003],
   'status': 'closed',
   'volume': 0.0,
   'markets': [],
   'meta-tags': [{'id': 385227477790005,
     'name': 'Politics',
     'type': 'SPORT',
     'url-name': 'politics'},
    {'id': 1302896445450017,
     'name': 'Next Labour Leader',
     'type': 'COMPETITION',
     'url-name': 'next-labour-leader'},
    {'id': 1529052331600003,
     'name': 'UK Politics',
     'type': 'COMPETITION',
     'url-name': 'uk-politics'}]},
  {'id': 29765170060200076,
   'name': "Any Player To Acheive Two Or More 147's Across All 4 Major Tournaments (Saudi, UK, Masters, World) (Max Payout\xa03\xa0Players)",
   'sport-id': 120,
   'start': '2025-04-02T08:59:00.000Z',
   'in-running-flag': False,
   'allow-live-betting': False,
   'category-id': [120, 292022482330036, 400798618290009],
   'status': 'closed',
   'volume': 257383.78794,
   'markets': [],
   'meta-tags': [{'id': 120,
     'name': 'Snooker',
     'type': 'SPORT',
     'url-name': 'snooker'},
    {'id': 292022482330036,
     'name': 'Block Trade',
     'type': 'OTHER',
     'url-name': 'block-trade'},
    {'id': 400798618290009,
     'name': 'World',
     'type': 'COUNTRY',
     'url-name': 'world'}]},
  {'id': 31293426439100061,
   'name': 'test',
   'sport-id': 8,
   'start': '2025-09-27T17:10:00.000Z',
   'in-running-flag': False,
   'allow-live-betting': True,
   'category-id': [8, 1862791962990016, 30631793272600054, 31293382129200047],
   'status': 'closed',
   'volume': 0.0,
   'markets': [],
   'meta-tags': [{'id': 8,
     'name': 'Golf',
     'type': 'SPORT',
     'url-name': 'golf'},
    {'id': 1862791962990016,
     'name': 'Ryder Cup',
     'type': 'COMPETITION',
     'url-name': 'ryder-cup'},
    {'id': 30631793272600054,
     'name': 'September 27th 2025',
     'type': 'DATE',
     'url-name': 'september-27th-2025'},
    {'id': 31293382129200047,
     'name': 'Day 2 Foursomes Correct Score',
     'type': 'OTHER',
     'url-name': 'day-2-foursomes-correct-score'}]},
  {'id': 31321268331600061,
   'name': 'Next Labour Deputy Leader',
   'sport-id': 385227477790005,
   'start': '2025-10-07T17:00:00.000Z',
   'in-running-flag': False,
   'allow-live-betting': False,
   'category-id': [385227477790005],
   'status': 'closed',
   'volume': 161404.95404,
   'markets': [],
   'meta-tags': [{'id': 385227477790005,
     'name': 'Politics',
     'type': 'SPORT',
     'url-name': 'politics'}]},
  {'id': 31380678522200061,
   'name': '2025 Buick LPGA Shanghai',
   'sport-id': 8,
   'start': '2025-10-12T23:59:00.000Z',
   'in-running-flag': False,
   'allow-live-betting': False,
   'category-id': [8, 423407498380010, 28233032556300084, 30119347090800038],
   'status': 'closed',
   'volume': 0.0,
   'markets': [],
   'meta-tags': [{'id': 8,
     'name': 'Golf',
     'type': 'SPORT',
     'url-name': 'golf'},
    {'id': 423407498380010,
     'name': 'China',
     'type': 'COUNTRY',
     'url-name': 'china'},
    {'id': 28233032556300084,
     'name': 'Buick LPGA Shanghai',
     'type': 'COMPETITION',
     'url-name': 'buick-lpga-shanghai'},
    {'id': 30119347090800038,
     'name': 'October 12th 2025',
     'type': 'DATE',
     'url-name': 'october-12th-2025'}]},
  {'id': 31380678358100061,
   'name': '2025 SAS Championship',
   'sport-id': 8,
   'start': '2025-10-12T23:59:00.000Z',
   'in-running-flag': False,
   'allow-live-betting': False,
   'category-id': [8, 1904152202480016, 28234894100700084, 30119347090800038],
   'status': 'closed',
   'volume': 0.0,
   'markets': [],
   'meta-tags': [{'id': 8,
     'name': 'Golf',
     'type': 'SPORT',
     'url-name': 'golf'},
    {'id': 1904152202480016,
     'name': 'United States of America',
     'type': 'COUNTRY',
     'url-name': 'united-states-of-america'},
    {'id': 28234894100700084,
     'name': 'SAS Championship',
     'type': 'COMPETITION',
     'url-name': 'sas-championship'},
    {'id': 30119347090800038,
     'name': 'October 12th 2025',
     'type': 'DATE',
     'url-name': 'october-12th-2025'}]},
  {'id': 31440780971800058,
   'name': 'DP World India Championship 2025 ',
   'sport-id': 8,
   'start': '2025-10-16T01:05:00.000Z',
   'in-running-flag': True,
   'allow-live-betting': True,
   'category-id': [8,
    410468520880009,
    489003593880009,
    645571519460013,
    30119351674200038,
    31440780969700047],
   'status': 'open',
   'volume': 2357558.92154,
   'markets': [{'live': True,
     'event-id': 31440780971800058,
     'id': 31440783308500058,
     'name': 'Winner',
     'product': 'EXCHANGE',
     'start': '2025-10-16T01:05:00.000Z',
     'status': 'open',
     'market-type': 'outright',
     'type': 'multirunner',
     'in-running-flag': True,
     'allow-live-betting': True,
     'volume': 2321958.5392,
     'back-overround': 149.59126,
     'number-of-winners': 1,
     'runners': [{'withdrawn': False,
       'prices': [{'available-amount': 79.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 7.0,
         'decimal-odds': 7.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 24.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 5.6,
         'decimal-odds': 5.6,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 27.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 5.4,
         'decimal-odds': 5.4,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 37.01033,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 13.5,
         'decimal-odds': 13.5,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 4.00074,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 21.0,
         'decimal-odds': 21.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 4.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 30.0,
         'decimal-odds': 30.0,
         'side': 'lay',
         'exchange-type': 'back-lay'}],
       'last-price-update-time': '2025-10-16T11:15:03.121Z',
       'event-id': 31440780971800058,
       'id': 31440783311601058,
       'market-id': 31440783308500058,
       'name': 'Tommy Fleetwood',
       'status': 'open',
       'volume': 36422.63003,
       'event-participant-id': 31440780981101058},
      {'withdrawn': False,
       'prices': [{'available-amount': 4.00074,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 8.4,
         'decimal-odds': 8.4,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 12.00223,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 8.2,
         'decimal-odds': 8.2,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 17.00317,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 8.0,
         'decimal-odds': 8.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 11.00204,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 8.8,
         'decimal-odds': 8.8,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 16.00298,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 9.0,
         'decimal-odds': 9.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 13.00242,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 10.5,
         'decimal-odds': 10.5,
         'side': 'lay',
         'exchange-type': 'back-lay'}],
       'last-price-update-time': '2025-10-16T10:41:43.846Z',
       'event-id': 31440780971800058,
       'id': 31440783311401058,
       'market-id': 31440783308500058,
       'name': 'Rory McIlroy',
       'status': 'open',
       'volume': 37935.26538,
       'event-participant-id': 31440780981000058},
      {'withdrawn': False,
       'prices': [{'available-amount': 2.00037,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 10.0,
         'decimal-odds': 10.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 2.00037,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 9.8,
         'decimal-odds': 9.8,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 24.00447,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 9.4,
         'decimal-odds': 9.4,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 21.00391,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 11.0,
         'decimal-odds': 11.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 15.00279,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 16.0,
         'decimal-odds': 16.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 4.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 65.0,
         'decimal-odds': 65.0,
         'side': 'lay',
         'exchange-type': 'back-lay'}],
       'last-price-update-time': '2025-10-16T11:11:32.282Z',
       'event-id': 31440780971800058,
       'id': 31440783309101058,
       'market-id': 31440783308500058,
       'name': 'Keita Nakajima',
       'status': 'open',
       'volume': 138787.26084,
       'event-participant-id': 31440780979000058},
      {'withdrawn': False,
       'prices': [{'available-amount': 48.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 15.0,
         'decimal-odds': 15.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 18.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 13.0,
         'decimal-odds': 13.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 51.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 10.0,
         'decimal-odds': 10.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 6.00112,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 20.0,
         'decimal-odds': 20.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 38.01061,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 24.0,
         'decimal-odds': 24.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 6.00112,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 29.0,
         'decimal-odds': 29.0,
         'side': 'lay',
         'exchange-type': 'back-lay'}],
       'last-price-update-time': '2025-10-16T11:10:39.536Z',
       'event-id': 31440780971800058,
       'id': 31440783309501058,
       'market-id': 31440783308500058,
       'name': 'Brian Harman',
       'status': 'open',
       'volume': 18507.99259,
       'event-participant-id': 31440780979500058},
      {'withdrawn': False,
       'prices': [{'available-amount': 16.00298,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 9.4,
         'decimal-odds': 9.4,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 58.0108,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 9.2,
         'decimal-odds': 9.2,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 31.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 8.2,
         'decimal-odds': 8.2,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 5.00093,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 11.0,
         'decimal-odds': 11.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 34.00633,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 11.5,
         'decimal-odds': 11.5,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 15.00279,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 16.0,
         'decimal-odds': 16.0,
         'side': 'lay',
         'exchange-type': 'back-lay'}],
       'last-price-update-time': '2025-10-16T11:12:18.522Z',
       'event-id': 31440780971800058,
       'id': 31440783309301058,
       'market-id': 31440783308500058,
       'name': 'Ben Griffin',
       'status': 'open',
       'volume': 16295.71443,
       'event-participant-id': 31440780979202058},
      {'withdrawn': False,
       'prices': [{'available-amount': 4.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 28.0,
         'decimal-odds': 28.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 7.0013,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 26.0,
         'decimal-odds': 26.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 3.99336,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 25.0,
         'decimal-odds': 25.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 4.00111,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 32.0,
         'decimal-odds': 32.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 10.98647,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 34.0,
         'decimal-odds': 34.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 5.99492,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 40.0,
         'decimal-odds': 40.0,
         'side': 'lay',
         'exchange-type': 'back-lay'}],
       'last-price-update-time': '2025-10-16T11:08:50.588Z',
       'event-id': 31440780971800058,
       'id': 31440783312100058,
       'market-id': 31440783308500058,
       'name': 'Viktor Hovland',
       'status': 'open',
       'volume': 40510.43811,
       'event-participant-id': 31440780981401058},
      {'withdrawn': False,
       'prices': [{'available-amount': 38.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 5.0,
         'decimal-odds': 5.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 31.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 4.8,
         'decimal-odds': 4.8,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 9.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 4.7,
         'decimal-odds': 4.7,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 5.00093,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 6.2,
         'decimal-odds': 6.2,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 4.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 8.0,
         'decimal-odds': 8.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 4.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 15.0,
         'decimal-odds': 15.0,
         'side': 'lay',
         'exchange-type': 'back-lay'}],
       'last-price-update-time': '2025-10-16T11:14:19.046Z',
       'event-id': 31440780971800058,
       'id': 31440783311900058,
       'market-id': 31440783308500058,
       'name': 'Shane Lowry',
       'status': 'open',
       'volume': 15935.33574,
       'event-participant-id': 31440780981201058},
      {'withdrawn': False,
       'prices': [{'available-amount': 2.00037,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 130.0,
         'decimal-odds': 130.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 2.00037,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 120.0,
         'decimal-odds': 120.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 3.99596,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 110.0,
         'decimal-odds': 110.0,
         'side': 'back',
         'exchange-type': 'back-lay'}],
       'last-price-update-time': '2025-10-16T11:02:30.134Z',
       'event-id': 31440780971800058,
       'id': 31440783309701058,
       'market-id': 31440783308500058,
       'name': 'Angel Ayora',
       'status': 'open',
       'volume': 21867.86556,
       'event-participant-id': 31440780979601058},
      {'withdrawn': False,
       'prices': [{'available-amount': 33.9656,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 32.0,
         'decimal-odds': 32.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 7.0,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 30.0,
         'decimal-odds': 30.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 50.00931,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 28.0,
         'decimal-odds': 28.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 7.99191,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 80.0,
         'decimal-odds': 80.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 8.00223,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 110.0,
         'decimal-odds': 110.0,
         'side': 'lay',
         'exchange-type': 'back-lay'},
        {'available-amount': 4.00111,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 350.0,
         'decimal-odds': 350.0,
         'side': 'lay',
         'exchange-type': 'back-lay'}],
       'last-price-update-time': '2025-10-16T11:10:39.027Z',
       'event-id': 31440780971800058,
       'id': 31440783322300058,
       'market-id': 31440783308500058,
       'name': 'Jorge Campillo',
       'status': 'open',
       'volume': 22588.26514,
       'event-participant-id': 31440780985301058},
      {'withdrawn': False,
       'prices': [{'available-amount': 3.00084,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 75.0,
         'decimal-odds': 75.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 1.99668,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 70.0,
         'decimal-odds': 70.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 13.00242,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',
         'odds': 55.0,
         'decimal-odds': 55.0,
         'side': 'back',
         'exchange-type': 'back-lay'},
        {'available-amount': 2.99563,
         'currency': 'GBP',
         'odds-type': 'DECIMAL',

In [44]:
# get specific event
# 'DP World India Championship 2025 '

event_id = '31440780971800058'
url = f"https://api.matchbook.com/edge/rest/events/{event_id}?exchange-type=back-lay&odds-type=DECIMAL&include-prices=true&price-depth=3&price-mode=expanded"

headers = {
    "accept": "application/json",
    'session-token': '681420_fd6b6c96b3e6dfedf0e82de77454c923'
}

response = requests.get(url, headers=headers)
print(response.text)

{"id":31440780971800058,"name":"DP World India Championship 2025 ","sport-id":8,"start":"2025-10-16T01:05:00.000Z","in-running-flag":true,"allow-live-betting":true,"category-id":[8,410468520880009,489003593880009,645571519460013,30119351674200038,31440780969700047],"status":"open","volume":2357558.92154,"markets":[{"live":true,"event-id":31440780971800058,"id":31440783308500058,"name":"Winner","product":"EXCHANGE","start":"2025-10-16T01:05:00.000Z","status":"open","market-type":"outright","type":"multirunner","in-running-flag":true,"allow-live-betting":true,"volume":2321958.5392,"back-overround":144.06467,"number-of-winners":1,"runners":[{"withdrawn":false,"prices":[{"available-amount":3.00000,"currency":"GBP","odds-type":"DECIMAL","odds":7.60000,"decimal-odds":7.60000,"side":"back","exchange-type":"back-lay"},{"available-amount":37.00000,"currency":"GBP","odds-type":"DECIMAL","odds":7.20000,"decimal-odds":7.20000,"side":"back","exchange-type":"back-lay"},{"available-amount":26.00000,"currency":"GBP","odds-type":"DECIMAL","odds":7.00000,"decimal-odds":7.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.00000,"currency":"GBP","odds-type":"DECIMAL","odds":8.00000,"decimal-odds":8.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":15.00000,"currency":"GBP","odds-type":"DECIMAL","odds":8.60000,"decimal-odds":8.60000,"side":"lay","exchange-type":"back-lay"},{"available-amount":19.00000,"currency":"GBP","odds-type":"DECIMAL","odds":8.80000,"decimal-odds":8.80000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:54:11.606Z","event-id":31440780971800058,"id":31440783311601058,"market-id":31440783308500058,"name":"Tommy Fleetwood","status":"open","volume":36422.63003,"event-participant-id":31440780981101058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":8.80000,"decimal-odds":8.80000,"side":"back","exchange-type":"back-lay"},{"available-amount":85.00000,"currency":"GBP","odds-type":"DECIMAL","odds":8.60000,"decimal-odds":8.60000,"side":"back","exchange-type":"back-lay"},{"available-amount":44.00000,"currency":"GBP","odds-type":"DECIMAL","odds":8.40000,"decimal-odds":8.40000,"side":"back","exchange-type":"back-lay"},{"available-amount":16.00298,"currency":"GBP","odds-type":"DECIMAL","odds":9.00000,"decimal-odds":9.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":48.00000,"currency":"GBP","odds-type":"DECIMAL","odds":9.20000,"decimal-odds":9.20000,"side":"lay","exchange-type":"back-lay"},{"available-amount":12.00000,"currency":"GBP","odds-type":"DECIMAL","odds":9.80000,"decimal-odds":9.80000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:52:18.825Z","event-id":31440780971800058,"id":31440783311401058,"market-id":31440783308500058,"name":"Rory McIlroy","status":"open","volume":37935.26538,"event-participant-id":31440780981000058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":11.00000,"decimal-odds":11.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":76.00000,"currency":"GBP","odds-type":"DECIMAL","odds":10.50000,"decimal-odds":10.50000,"side":"back","exchange-type":"back-lay"},{"available-amount":37.00689,"currency":"GBP","odds-type":"DECIMAL","odds":10.00000,"decimal-odds":10.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":28.00000,"currency":"GBP","odds-type":"DECIMAL","odds":14.00000,"decimal-odds":14.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":15.00279,"currency":"GBP","odds-type":"DECIMAL","odds":16.00000,"decimal-odds":16.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":6.00000,"currency":"GBP","odds-type":"DECIMAL","odds":65.00000,"decimal-odds":65.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:49:15.643Z","event-id":31440780971800058,"id":31440783309101058,"market-id":31440783308500058,"name":"Keita Nakajima","status":"open","volume":138787.26084,"event-participant-id":31440780979000058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":17.00000,"decimal-odds":17.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":23.00000,"currency":"GBP","odds-type":"DECIMAL","odds":16.50000,"decimal-odds":16.50000,"side":"back","exchange-type":"back-lay"},{"available-amount":29.00000,"currency":"GBP","odds-type":"DECIMAL","odds":16.00000,"decimal-odds":16.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":32.00000,"currency":"GBP","odds-type":"DECIMAL","odds":19.50000,"decimal-odds":19.50000,"side":"lay","exchange-type":"back-lay"},{"available-amount":13.00242,"currency":"GBP","odds-type":"DECIMAL","odds":20.00000,"decimal-odds":20.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":16.00000,"currency":"GBP","odds-type":"DECIMAL","odds":23.00000,"decimal-odds":23.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:50:11.562Z","event-id":31440780971800058,"id":31440783309501058,"market-id":31440783308500058,"name":"Brian Harman","status":"open","volume":18507.99259,"event-participant-id":31440780979500058},{"withdrawn":false,"prices":[{"available-amount":95.00000,"currency":"GBP","odds-type":"DECIMAL","odds":11.00000,"decimal-odds":11.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":107.00000,"currency":"GBP","odds-type":"DECIMAL","odds":10.50000,"decimal-odds":10.50000,"side":"back","exchange-type":"back-lay"},{"available-amount":55.00000,"currency":"GBP","odds-type":"DECIMAL","odds":9.80000,"decimal-odds":9.80000,"side":"back","exchange-type":"back-lay"},{"available-amount":34.00633,"currency":"GBP","odds-type":"DECIMAL","odds":11.50000,"decimal-odds":11.50000,"side":"lay","exchange-type":"back-lay"},{"available-amount":22.00410,"currency":"GBP","odds-type":"DECIMAL","odds":16.00000,"decimal-odds":16.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":16.00000,"currency":"GBP","odds-type":"DECIMAL","odds":19.00000,"decimal-odds":19.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:53:11.425Z","event-id":31440780971800058,"id":31440783309301058,"market-id":31440783308500058,"name":"Ben Griffin","status":"open","volume":16295.71443,"event-participant-id":31440780979202058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":36.00000,"decimal-odds":36.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.00000,"currency":"GBP","odds-type":"DECIMAL","odds":34.00000,"decimal-odds":34.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":6.00000,"currency":"GBP","odds-type":"DECIMAL","odds":32.00000,"decimal-odds":32.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":38.00000,"decimal-odds":38.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":1.99831,"currency":"GBP","odds-type":"DECIMAL","odds":40.00000,"decimal-odds":40.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":5.00000,"currency":"GBP","odds-type":"DECIMAL","odds":48.00000,"decimal-odds":48.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:52:18.426Z","event-id":31440780971800058,"id":31440783312100058,"market-id":31440783308500058,"name":"Viktor Hovland","status":"open","volume":40510.43811,"event-participant-id":31440780981401058},{"withdrawn":false,"prices":[{"available-amount":46.00000,"currency":"GBP","odds-type":"DECIMAL","odds":4.50000,"decimal-odds":4.50000,"side":"back","exchange-type":"back-lay"},{"available-amount":47.00000,"currency":"GBP","odds-type":"DECIMAL","odds":4.40000,"decimal-odds":4.40000,"side":"back","exchange-type":"back-lay"},{"available-amount":121.00000,"currency":"GBP","odds-type":"DECIMAL","odds":4.30000,"decimal-odds":4.30000,"side":"back","exchange-type":"back-lay"},{"available-amount":75.00000,"currency":"GBP","odds-type":"DECIMAL","odds":4.70000,"decimal-odds":4.70000,"side":"lay","exchange-type":"back-lay"},{"available-amount":238.00000,"currency":"GBP","odds-type":"DECIMAL","odds":4.80000,"decimal-odds":4.80000,"side":"lay","exchange-type":"back-lay"},{"available-amount":110.00000,"currency":"GBP","odds-type":"DECIMAL","odds":4.90000,"decimal-odds":4.90000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:54:36.272Z","event-id":31440780971800058,"id":31440783311900058,"market-id":31440783308500058,"name":"Shane Lowry","status":"open","volume":15935.33574,"event-participant-id":31440780981201058},{"withdrawn":false,"prices":[{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":130.00000,"decimal-odds":130.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":120.00000,"decimal-odds":120.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99596,"currency":"GBP","odds-type":"DECIMAL","odds":110.00000,"decimal-odds":110.00000,"side":"back","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:02:30.134Z","event-id":31440780971800058,"id":31440783309701058,"market-id":31440783308500058,"name":"Angel Ayora","status":"open","volume":21867.86556,"event-participant-id":31440780979601058},{"withdrawn":false,"prices":[{"available-amount":33.96560,"currency":"GBP","odds-type":"DECIMAL","odds":32.00000,"decimal-odds":32.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":7.00000,"currency":"GBP","odds-type":"DECIMAL","odds":30.00000,"decimal-odds":30.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":48.00000,"currency":"GBP","odds-type":"DECIMAL","odds":28.00000,"decimal-odds":28.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":7.99191,"currency":"GBP","odds-type":"DECIMAL","odds":80.00000,"decimal-odds":80.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":8.00223,"currency":"GBP","odds-type":"DECIMAL","odds":110.00000,"decimal-odds":110.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00111,"currency":"GBP","odds-type":"DECIMAL","odds":350.00000,"decimal-odds":350.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:49:39.738Z","event-id":31440780971800058,"id":31440783322300058,"market-id":31440783308500058,"name":"Jorge Campillo","status":"open","volume":22588.26514,"event-participant-id":31440780985301058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":85.00000,"decimal-odds":85.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":80.00000,"decimal-odds":80.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.00084,"currency":"GBP","odds-type":"DECIMAL","odds":75.00000,"decimal-odds":75.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99563,"currency":"GBP","odds-type":"DECIMAL","odds":180.00000,"decimal-odds":180.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:52:21.168Z","event-id":31440780971800058,"id":31440783328201058,"market-id":31440783308500058,"name":"Jordan Smith","status":"open","volume":30419.54719,"event-participant-id":31440780989901058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":55.00000,"decimal-odds":55.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":48.00000,"decimal-odds":48.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":6.00112,"currency":"GBP","odds-type":"DECIMAL","odds":46.00000,"decimal-odds":46.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":1.99668,"currency":"GBP","odds-type":"DECIMAL","odds":60.00000,"decimal-odds":60.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":65.00000,"decimal-odds":65.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":70.00000,"decimal-odds":70.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:53:59.696Z","event-id":31440780971800058,"id":31440783331100058,"market-id":31440783308500058,"name":"Jayden Trey Schaper","status":"open","volume":28138.69268,"event-participant-id":31440780992000058},{"withdrawn":false,"prices":[{"available-amount":5.00000,"currency":"GBP","odds-type":"DECIMAL","odds":400.00000,"decimal-odds":400.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":300.00000,"decimal-odds":300.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.00056,"currency":"GBP","odds-type":"DECIMAL","odds":170.00000,"decimal-odds":170.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":680.00000,"decimal-odds":680.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":1000.00000,"decimal-odds":1000.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:42:09.565Z","event-id":31440780971800058,"id":31440783308900058,"market-id":31440783308500058,"name":"John Parry","status":"open","volume":22577.87945,"event-participant-id":31440780978600058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":27.00000,"decimal-odds":27.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":9.00000,"currency":"GBP","odds-type":"DECIMAL","odds":26.00000,"decimal-odds":26.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":8.00000,"currency":"GBP","odds-type":"DECIMAL","odds":23.00000,"decimal-odds":23.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00056,"currency":"GBP","odds-type":"DECIMAL","odds":28.00000,"decimal-odds":28.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":10.98175,"currency":"GBP","odds-type":"DECIMAL","odds":29.00000,"decimal-odds":29.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":5.00000,"currency":"GBP","odds-type":"DECIMAL","odds":30.00000,"decimal-odds":30.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:34:43.536Z","event-id":31440780971800058,"id":31440783312300058,"market-id":31440783308500058,"name":"Michael Kim","status":"open","volume":21390.46264,"event-participant-id":31440780981600058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":100.00000,"decimal-odds":100.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":1.99798,"currency":"GBP","odds-type":"DECIMAL","odds":95.00000,"decimal-odds":95.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":70.00000,"decimal-odds":70.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99746,"currency":"GBP","odds-type":"DECIMAL","odds":330.00000,"decimal-odds":330.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:41:49.194Z","event-id":31440780971800058,"id":31440783329801058,"market-id":31440783308500058,"name":"Andy Sullivan","status":"open","volume":17058.74453,"event-participant-id":31440780991101058},{"withdrawn":false,"prices":[{"available-amount":6.00000,"currency":"GBP","odds-type":"DECIMAL","odds":75.00000,"decimal-odds":75.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":70.00000,"decimal-odds":70.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":60.00000,"decimal-odds":60.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":120.00000,"decimal-odds":120.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":5.99393,"currency":"GBP","odds-type":"DECIMAL","odds":150.00000,"decimal-odds":150.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":290.00000,"decimal-odds":290.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:52:20.274Z","event-id":31440780971800058,"id":31440783312901058,"market-id":31440783308500058,"name":"Adrien Saddier","status":"open","volume":26905.54207,"event-participant-id":31440780982001058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":80.00000,"decimal-odds":80.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00056,"currency":"GBP","odds-type":"DECIMAL","odds":70.00000,"decimal-odds":70.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":5.00000,"currency":"GBP","odds-type":"DECIMAL","odds":65.00000,"decimal-odds":65.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99502,"currency":"GBP","odds-type":"DECIMAL","odds":85.00000,"decimal-odds":85.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:45:49.033Z","event-id":31440780971800058,"id":31440783323601058,"market-id":31440783308500058,"name":"Anirban Lahiri","status":"open","volume":26882.73531,"event-participant-id":31440780986201058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":29.00000,"decimal-odds":29.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99596,"currency":"GBP","odds-type":"DECIMAL","odds":28.00000,"decimal-odds":28.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":9.00000,"currency":"GBP","odds-type":"DECIMAL","odds":27.00000,"decimal-odds":27.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.00000,"currency":"GBP","odds-type":"DECIMAL","odds":50.00000,"decimal-odds":50.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":7.00000,"currency":"GBP","odds-type":"DECIMAL","odds":55.00000,"decimal-odds":55.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00074,"currency":"GBP","odds-type":"DECIMAL","odds":90.00000,"decimal-odds":90.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:54:15.516Z","event-id":31440780971800058,"id":31440783332300058,"market-id":31440783308500058,"name":"Joost Luiten","status":"open","volume":29887.14725,"event-participant-id":31440780992801058},{"withdrawn":false,"prices":[{"available-amount":7.00000,"currency":"GBP","odds-type":"DECIMAL","odds":60.00000,"decimal-odds":60.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":55.00000,"decimal-odds":55.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":10.00000,"currency":"GBP","odds-type":"DECIMAL","odds":50.00000,"decimal-odds":50.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":6.00112,"currency":"GBP","odds-type":"DECIMAL","odds":180.00000,"decimal-odds":180.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":2.00037,"currency":"GBP","odds-type":"DECIMAL","odds":200.00000,"decimal-odds":200.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00074,"currency":"GBP","odds-type":"DECIMAL","odds":250.00000,"decimal-odds":250.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:44:13.099Z","event-id":31440780971800058,"id":31440783312500058,"market-id":31440783308500058,"name":"Thriston Lawrence","status":"open","volume":25056.84195,"event-

In [45]:
[market['name'] for market in response.json()['markets']]
# also has a merkets endpoint: 
# url = "https://api.matchbook.com/edge/rest/events/event_id/markets?offset=0&per-page=20&states=open%2Csuspended&exchange-type=back-lay&odds-type=DECIMAL&include-prices=false&price-depth=3&price-mode=expanded&exclude-mirrored-prices=false"

['Winner', 'Top 5 Finish', 'Top 10 Finish']

In [46]:
next(market for market in response.json()['markets'] if market['name'] == 'Winner')

{'live': True,
 'event-id': 31440780971800058,
 'id': 31440783308500058,
 'name': 'Winner',
 'product': 'EXCHANGE',
 'start': '2025-10-16T01:05:00.000Z',
 'status': 'open',
 'market-type': 'outright',
 'type': 'multirunner',
 'in-running-flag': True,
 'allow-live-betting': True,
 'volume': 2321958.5392,
 'back-overround': 144.06467,
 'number-of-winners': 1,
 'runners': [{'withdrawn': False,
   'prices': [{'available-amount': 3.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 7.6,
     'decimal-odds': 7.6,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 37.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 7.2,
     'decimal-odds': 7.2,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 26.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 7.0,
     'decimal-odds': 7.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.0,
     'decimal-odds': 8.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 15.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.6,
     'decimal-odds': 8.6,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 19.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.8,
     'decimal-odds': 8.8,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:54:11.606Z',
   'event-id': 31440780971800058,
   'id': 31440783311601058,
   'market-id': 31440783308500058,
   'name': 'Tommy Fleetwood',
   'status': 'open',
   'volume': 36422.63003,
   'event-participant-id': 31440780981101058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.8,
     'decimal-odds': 8.8,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 85.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.6,
     'decimal-odds': 8.6,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 44.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.4,
     'decimal-odds': 8.4,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 16.00298,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 9.0,
     'decimal-odds': 9.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 48.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 9.2,
     'decimal-odds': 9.2,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 12.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 9.8,
     'decimal-odds': 9.8,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:52:18.825Z',
   'event-id': 31440780971800058,
   'id': 31440783311401058,
   'market-id': 31440783308500058,
   'name': 'Rory McIlroy',
   'status': 'open',
   'volume': 37935.26538,
   'event-participant-id': 31440780981000058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 11.0,
     'decimal-odds': 11.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 76.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 10.5,
     'decimal-odds': 10.5,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 37.00689,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 10.0,
     'decimal-odds': 10.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 28.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 14.0,
     'decimal-odds': 14.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 15.00279,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 16.0,
     'decimal-odds': 16.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 6.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 65.0,
     'decimal-odds': 65.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:49:15.643Z',
   'event-id': 31440780971800058,
   'id': 31440783309101058,
   'market-id': 31440783308500058,
   'name': 'Keita Nakajima',
   'status': 'open',
   'volume': 138787.26084,
   'event-participant-id': 31440780979000058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 17.0,
     'decimal-odds': 17.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 23.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 16.5,
     'decimal-odds': 16.5,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 29.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 16.0,
     'decimal-odds': 16.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 32.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 19.5,
     'decimal-odds': 19.5,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 13.00242,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 20.0,
     'decimal-odds': 20.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 16.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 23.0,
     'decimal-odds': 23.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:50:11.562Z',
   'event-id': 31440780971800058,
   'id': 31440783309501058,
   'market-id': 31440783308500058,
   'name': 'Brian Harman',
   'status': 'open',
   'volume': 18507.99259,
   'event-participant-id': 31440780979500058},
  {'withdrawn': False,
   'prices': [{'available-amount': 95.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 11.0,
     'decimal-odds': 11.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 107.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 10.5,
     'decimal-odds': 10.5,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 55.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 9.8,
     'decimal-odds': 9.8,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 34.00633,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 11.5,
     'decimal-odds': 11.5,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 22.0041,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 16.0,
     'decimal-odds': 16.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 16.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 19.0,
     'decimal-odds': 19.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:53:11.425Z',
   'event-id': 31440780971800058,
   'id': 31440783309301058,
   'market-id': 31440783308500058,
   'name': 'Ben Griffin',
   'status': 'open',
   'volume': 16295.71443,
   'event-participant-id': 31440780979202058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 36.0,
     'decimal-odds': 36.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 34.0,
     'decimal-odds': 34.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 6.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 32.0,
     'decimal-odds': 32.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 38.0,
     'decimal-odds': 38.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 1.99831,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 40.0,
     'decimal-odds': 40.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 5.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 48.0,
     'decimal-odds': 48.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:52:18.426Z',
   'event-id': 31440780971800058,
   'id': 31440783312100058,
   'market-id': 31440783308500058,
   'name': 'Viktor Hovland',
   'status': 'open',
   'volume': 40510.43811,
   'event-participant-id': 31440780981401058},
  {'withdrawn': False,
   'prices': [{'available-amount': 46.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.5,
     'decimal-odds': 4.5,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 47.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.4,
     'decimal-odds': 4.4,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 121.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.3,
     'decimal-odds': 4.3,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 75.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.7,
     'decimal-odds': 4.7,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 238.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.8,
     'decimal-odds': 4.8,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 110.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.9,
     'decimal-odds': 4.9,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:54:36.272Z',
   'event-id': 31440780971800058,
   'id': 31440783311900058,
   'market-id': 31440783308500058,
   'name': 'Shane Lowry',
   'status': 'open',
   'volume': 15935.33574,
   'event-participant-id': 31440780981201058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.00037,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 130.0,
     'decimal-odds': 130.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.00037,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 120.0,
     'decimal-odds': 120.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.99596,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 110.0,
     'decimal-odds': 110.0,
     'side': 'back',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:02:30.134Z',
   'event-id': 31440780971800058,
   'id': 31440783309701058,
   'market-id': 31440783308500058,
   'name': 'Angel Ayora',
   'status': 'open',
   'volume': 21867.86556,
   'event-participant-id': 31440780979601058},
  {'withdrawn': False,
   'prices': [{'available-amount': 33.9656,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 32.0,
     'decimal-odds': 32.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 7.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 30.0,
     'decimal-odds': 30.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 48.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 28.0,
     'decimal-odds': 28.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 7.99191,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 80.0,
     'decimal-odds': 80.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 8.00223,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 110.0,
     'decimal-odds': 110.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.00111,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 350.0,
     'decimal-odds': 350.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:49:39.738Z',
   'event-id': 31440780971800058,
   'id': 31440783322300058,
   'market-id': 31440783308500058,
   'name': 'Jorge Campillo',
   'status': 'open',
   'volume': 22588.26514,
   'event-participant-id': 31440780985301058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 85.0,
     'decimal-odds': 85.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 80.0,
     'decimal-odds': 80.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.00084,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 75.0,
     'decimal-odds': 75.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.99563,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 180.0,
     'decimal-odds': 180.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:52:21.168Z',
   'event-id': 31440780971800058,
   'id': 31440783328201058,
   'market-id': 31440783308500058,
   'name': 'Jordan Smith',
   'status': 'open',
   'volume': 30419.54719,
   'event-participant-id': 31440780989901058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 55.0,
     'decimal-odds': 55.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 48.0,
     'decimal-odds': 48.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 6.00112,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 46.0,
     'decimal-odds': 46.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 1.99668,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 60.0,
     'decimal-odds': 60.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.00037,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 65.0,
     'decimal-odds': 65.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 70.0,
     'decimal-odds': 70.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:53:59.696Z',
   'event-id': 31440780971800058,
   'id': 31440783331100058,
   'market-id': 31440783308500058,
   'name': 'Jayden Trey Schaper',
   'status': 'open',
   'volume': 28138.69268,
   'event-participant-id': 31440780992000058},
  {'withdrawn': False,
   'prices': [{'available-amount': 5.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 400.0,
     'decimal-odds': 400.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 300.0,
     'decimal-odds': 300.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.00056,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 170.0,
     'decimal-odds': 170.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 680.0,
     'decimal-odds': 680.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 1000.0,
     'decimal-odds': 1000.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:42:09.565Z',
   'event-id': 31440780971800058,
   'id': 31440783308900058,
   'market-id': 31440783308500058,
   'name': 'John Parry',
   'status': 'open',
   'volume': 22577.87945,
   'event-participant-id': 31440780978600058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 27.0,
     'decimal-odds': 27.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 9.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 26.0,
     'decimal-odds': 26.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 8.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 23.0,
     'decimal-odds': 23.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.00056,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 28.0,
     'decimal-odds': 28.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 10.98175,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 29.0,
     'decimal-odds': 29.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 5.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 30.0,
     'decimal-odds': 30.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:34:43.536Z',
   'event-id': 31440780971800058,
   'id': 31440783312300058,
   'market-id': 31440783308500058,
   'name': 'Michael Kim',
   'status': 'open',
   'volume': 21390.46264,
   'event-participant-id': 31440780981600058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 100.0,
     'decimal-odds': 100.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 1.99798,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 95.0,
     'decimal-odds': 95.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 70.0,
     'decimal-odds': 70.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.99746,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 330.0,
     'decimal-odds': 330.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:41:49.194Z',
   'event-id': 31440780971800058,
   'id': 31440783329801058,
   'market-id': 31440783308500058,
   'name': 'Andy Sullivan',
   'status': 'open',
   'volume': 17058.74453,
   'event-participant-id': 31440780991101058},
  {'withdrawn': False,
   'prices': [{'available-amount': 6.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 75.0,
     'decimal-odds': 75.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 70.0,
     'decimal-odds': 70.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 60.0,
     'decimal-odds': 60.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.00037,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 120.0,
     'decimal-odds': 120.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 5.99393,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 150.0,
     'decimal-odds': 150.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 290.0,
     'decimal-odds': 290.0,
     'side': 'lay',

In [47]:
metadata = []
pricedata = []

runners = next(market['runners'] for market in response.json()['markets'] if market['name'] == 'Winner')

for record in runners:
    
    keydata = {k: v for k, v in record.items() if k != 'prices'}
    prices = pd.DataFrame(record['prices'])
    prices['id'] = keydata['id']
    
    metadata.append(keydata)
    pricedata.append(prices)
    
runner_prices = pd.DataFrame(metadata).merge(pd.concat(pricedata), how='left', on='id')
runner_prices

,withdrawn,last-price-update-time,event-id,id,market-id,name,status,volume,event-participant-id,available-amount,currency,odds-type,odds,decimal-odds,side,exchange-type
0,False,2025-10-16T11:54:11.606Z,31440780971800058,31440783311601058,31440783308500058,Tommy Fleetwood,open,36422.63003,31440780981101058,3.00000,GBP,DECIMAL,7.6,7.6,back,back-lay
1,False,2025-10-16T11:54:11.606Z,31440780971800058,31440783311601058,31440783308500058,Tommy Fleetwood,open,36422.63003,31440780981101058,37.00000,GBP,DECIMAL,7.2,7.2,back,back-lay
2,False,2025-10-16T11:54:11.606Z,31440780971800058,31440783311601058,31440783308500058,Tommy Fleetwood,open,36422.63003,31440780981101058,26.00000,GBP,DECIMAL,7.0,7.0,back,back-lay
3,False,2025-10-16T11:54:11.606Z,31440780971800058,31440783311601058,31440783308500058,Tommy Fleetwood,open,36422.63003,31440780981101058,3.00000,GBP,DECIMAL,8.0,8.0,lay,back-lay
4,False,2025-10-16T11:54:11.606Z,31440780971800058,31440783311601058,31440783308500058,Tommy Fleetwood,open,36422.63003,31440780981101058,15.00000,GBP,DECIMAL,8.6,8.6,lay,back-lay
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,False,2025-10-16T01:05:37.731Z,31440780971800058,31441065322202058,31440783308500058,Chiragh Kumar,open,0.00000,31441065320600058,2.99738,GBP,DECIMAL,410.0,410.0,back,back-lay
507,False,2025-10-16T01:05:37.731Z,31440780971800058,31441065322202058,31440783308500058,Chiragh Kumar,open,0.00000,31441065320600058,3.99650,GBP,DECIMAL,300.0,300.0,back,back-lay
508,False,2025-10-16T01:05:42.038Z,31440780971800058,31441074678802058,31440783308500058,Udayan Mane,open,0.00000,31441074677700058,1.99825,GBP,DECIMAL,1000.0,1000.0,back,back-lay
509,False,2025-10-16T01:05:42.038Z,31440780971800058,31441074678802058,31440783308500058,Udayan Mane,open,0.00000,31441074677700058,2.99738,GBP,DECIMAL,410.0,410.0,back,back-lay
510,False,2025-10-16T01:05:42.038Z,31440780971800058,31441074678802058,31440783308500058,Udayan Mane,open,0.00000,31441074677700058,3.99650,GBP,DECIMAL,300.0,300.0,back,back-lay

In [55]:
# get runners
event_id = '31440780971800058'
market_id = '31440783308500058'
url = f"https://api.matchbook.com/edge/rest/events/{event_id}/markets/{market_id}/runners?states=open%2Csuspended&include-withdrawn=true&include-prices=true&price-depth=3&price-mode=expanded&exchange-type=back-lay&odds-type=DECIMAL&exclude-mirrored-prices=false"

headers = {
    "accept": "application/json",
    'session-token': '681420_fd6b6c96b3e6dfedf0e82de77454c923'
}

response = requests.get(url, headers=headers)
print(response.text)

{"runners":[{"withdrawn":false,"prices":[{"available-amount":19.99075,"currency":"GBP","odds-type":"DECIMAL","odds":7.60000,"decimal-odds":7.60000,"side":"back","exchange-type":"back-lay"},{"available-amount":36.98288,"currency":"GBP","odds-type":"DECIMAL","odds":7.20000,"decimal-odds":7.20000,"side":"back","exchange-type":"back-lay"},{"available-amount":35.00000,"currency":"GBP","odds-type":"DECIMAL","odds":7.00000,"decimal-odds":7.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99862,"currency":"GBP","odds-type":"DECIMAL","odds":8.00000,"decimal-odds":8.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":15.99260,"currency":"GBP","odds-type":"DECIMAL","odds":8.20000,"decimal-odds":8.20000,"side":"lay","exchange-type":"back-lay"},{"available-amount":18.99121,"currency":"GBP","odds-type":"DECIMAL","odds":8.60000,"decimal-odds":8.60000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:16:42.633Z","event-id":31440780971800058,"id":31440783311601058,"market-id":31440783308500058,"name":"Tommy Fleetwood","status":"open","volume":36405.77748,"event-participant-id":31440780981101058},{"withdrawn":false,"prices":[{"available-amount":6.00000,"currency":"GBP","odds-type":"DECIMAL","odds":8.80000,"decimal-odds":8.80000,"side":"back","exchange-type":"back-lay"},{"available-amount":81.96206,"currency":"GBP","odds-type":"DECIMAL","odds":8.60000,"decimal-odds":8.60000,"side":"back","exchange-type":"back-lay"},{"available-amount":42.98011,"currency":"GBP","odds-type":"DECIMAL","odds":8.40000,"decimal-odds":8.40000,"side":"back","exchange-type":"back-lay"},{"available-amount":15.99558,"currency":"GBP","odds-type":"DECIMAL","odds":9.00000,"decimal-odds":9.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":47.97779,"currency":"GBP","odds-type":"DECIMAL","odds":9.20000,"decimal-odds":9.20000,"side":"lay","exchange-type":"back-lay"},{"available-amount":11.99445,"currency":"GBP","odds-type":"DECIMAL","odds":9.80000,"decimal-odds":9.80000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:10:46.709Z","event-id":31440780971800058,"id":31440783311401058,"market-id":31440783308500058,"name":"Rory McIlroy","status":"open","volume":37917.71295,"event-participant-id":31440780981000058},{"withdrawn":false,"prices":[{"available-amount":3.00000,"currency":"GBP","odds-type":"DECIMAL","odds":11.50000,"decimal-odds":11.50000,"side":"back","exchange-type":"back-lay"},{"available-amount":5.99722,"currency":"GBP","odds-type":"DECIMAL","odds":11.00000,"decimal-odds":11.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":21.98982,"currency":"GBP","odds-type":"DECIMAL","odds":10.50000,"decimal-odds":10.50000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":12.00000,"decimal-odds":12.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":32.98473,"currency":"GBP","odds-type":"DECIMAL","odds":12.50000,"decimal-odds":12.50000,"side":"lay","exchange-type":"back-lay"},{"available-amount":17.99167,"currency":"GBP","odds-type":"DECIMAL","odds":13.00000,"decimal-odds":13.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:17:35.956Z","event-id":31440780971800058,"id":31440783309101058,"market-id":31440783308500058,"name":"Keita Nakajima","status":"open","volume":138723.04474,"event-participant-id":31440780979000058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":17.50000,"decimal-odds":17.50000,"side":"back","exchange-type":"back-lay"},{"available-amount":21.98982,"currency":"GBP","odds-type":"DECIMAL","odds":16.50000,"decimal-odds":16.50000,"side":"back","exchange-type":"back-lay"},{"available-amount":22.00000,"currency":"GBP","odds-type":"DECIMAL","odds":16.00000,"decimal-odds":16.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":6.99676,"currency":"GBP","odds-type":"DECIMAL","odds":18.00000,"decimal-odds":18.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":25.98797,"currency":"GBP","odds-type":"DECIMAL","odds":19.50000,"decimal-odds":19.50000,"side":"lay","exchange-type":"back-lay"},{"available-amount":12.99640,"currency":"GBP","odds-type":"DECIMAL","odds":20.00000,"decimal-odds":20.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:17:33.749Z","event-id":31440780971800058,"id":31440783309501058,"market-id":31440783308500058,"name":"Brian Harman","status":"open","volume":18499.42904,"event-participant-id":31440780979500058},{"withdrawn":false,"prices":[{"available-amount":108.94957,"currency":"GBP","odds-type":"DECIMAL","odds":11.00000,"decimal-odds":11.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":108.94957,"currency":"GBP","odds-type":"DECIMAL","odds":10.50000,"decimal-odds":10.50000,"side":"back","exchange-type":"back-lay"},{"available-amount":56.97362,"currency":"GBP","odds-type":"DECIMAL","odds":9.80000,"decimal-odds":9.80000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":12.00000,"decimal-odds":12.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":18.99121,"currency":"GBP","odds-type":"DECIMAL","odds":12.50000,"decimal-odds":12.50000,"side":"lay","exchange-type":"back-lay"},{"available-amount":45.97872,"currency":"GBP","odds-type":"DECIMAL","odds":13.00000,"decimal-odds":13.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:16:33.212Z","event-id":31440780971800058,"id":31440783309301058,"market-id":31440783308500058,"name":"Ben Griffin","status":"open","volume":16288.17449,"event-participant-id":31440780979202058},{"withdrawn":false,"prices":[{"available-amount":2.99862,"currency":"GBP","odds-type":"DECIMAL","odds":34.00000,"decimal-odds":34.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":12.99398,"currency":"GBP","odds-type":"DECIMAL","odds":32.00000,"decimal-odds":32.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":7.00000,"currency":"GBP","odds-type":"DECIMAL","odds":28.00000,"decimal-odds":28.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99815,"currency":"GBP","odds-type":"DECIMAL","odds":38.00000,"decimal-odds":38.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":1.99738,"currency":"GBP","odds-type":"DECIMAL","odds":40.00000,"decimal-odds":40.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.99768,"currency":"GBP","odds-type":"DECIMAL","odds":48.00000,"decimal-odds":48.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:16:54.709Z","event-id":31440780971800058,"id":31440783312100058,"market-id":31440783308500058,"name":"Viktor Hovland","status":"open","volume":40491.69416,"event-participant-id":31440780981401058},{"withdrawn":false,"prices":[{"available-amount":60.97178,"currency":"GBP","odds-type":"DECIMAL","odds":4.50000,"decimal-odds":4.50000,"side":"back","exchange-type":"back-lay"},{"available-amount":52.97548,"currency":"GBP","odds-type":"DECIMAL","odds":4.40000,"decimal-odds":4.40000,"side":"back","exchange-type":"back-lay"},{"available-amount":262.00000,"currency":"GBP","odds-type":"DECIMAL","odds":4.30000,"decimal-odds":4.30000,"side":"back","exchange-type":"back-lay"},{"available-amount":61.00000,"currency":"GBP","odds-type":"DECIMAL","odds":4.60000,"decimal-odds":4.60000,"side":"lay","exchange-type":"back-lay"},{"available-amount":261.00000,"currency":"GBP","odds-type":"DECIMAL","odds":4.70000,"decimal-odds":4.70000,"side":"lay","exchange-type":"back-lay"},{"available-amount":237.88988,"currency":"GBP","odds-type":"DECIMAL","odds":4.80000,"decimal-odds":4.80000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:15:25.287Z","event-id":31440780971800058,"id":31440783311900058,"market-id":31440783308500058,"name":"Shane Lowry","status":"open","volume":15927.96255,"event-participant-id":31440780981201058},{"withdrawn":false,"prices":[{"available-amount":1.99945,"currency":"GBP","odds-type":"DECIMAL","odds":130.00000,"decimal-odds":130.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":1.99945,"currency":"GBP","odds-type":"DECIMAL","odds":120.00000,"decimal-odds":120.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99411,"currency":"GBP","odds-type":"DECIMAL","odds":110.00000,"decimal-odds":110.00000,"side":"back","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:02:30.134Z","event-id":31440780971800058,"id":31440783309701058,"market-id":31440783308500058,"name":"Angel Ayora","status":"open","volume":21857.74742,"event-participant-id":31440780979601058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":38.00000,"decimal-odds":38.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.00000,"currency":"GBP","odds-type":"DECIMAL","odds":36.00000,"decimal-odds":36.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":18.97200,"currency":"GBP","odds-type":"DECIMAL","odds":32.00000,"decimal-odds":32.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":7.98821,"currency":"GBP","odds-type":"DECIMAL","odds":80.00000,"decimal-odds":80.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":8.99835,"currency":"GBP","odds-type":"DECIMAL","odds":110.00000,"decimal-odds":110.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":350.00000,"decimal-odds":350.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:17:37.583Z","event-id":31440780971800058,"id":31440783322300058,"market-id":31440783308500058,"name":"Jorge Campillo","status":"open","volume":22577.81367,"event-participant-id":31440780985301058},{"withdrawn":false,"prices":[{"available-amount":1.99908,"currency":"GBP","odds-type":"DECIMAL","odds":85.00000,"decimal-odds":85.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99815,"currency":"GBP","odds-type":"DECIMAL","odds":80.00000,"decimal-odds":80.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99945,"currency":"GBP","odds-type":"DECIMAL","odds":75.00000,"decimal-odds":75.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99425,"currency":"GBP","odds-type":"DECIMAL","odds":180.00000,"decimal-odds":180.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:52:21.168Z","event-id":31440780971800058,"id":31440783328201058,"market-id":31440783308500058,"name":"Jordan Smith","status":"open","volume":30405.47223,"event-participant-id":31440780989901058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":60.00000,"decimal-odds":60.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.00000,"currency":"GBP","odds-type":"DECIMAL","odds":55.00000,"decimal-odds":55.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":11.99668,"currency":"GBP","odds-type":"DECIMAL","odds":46.00000,"decimal-odds":46.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":13.00000,"currency":"GBP","odds-type":"DECIMAL","odds":85.00000,"decimal-odds":85.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:10:11.521Z","event-id":31440780971800058,"id":31440783331100058,"market-id":31440783308500058,"name":"Jayden Trey Schaper","status":"open","volume":28125.67307,"event-participant-id":31440780992000058},{"withdrawn":false,"prices":[{"available-amount":4.99768,"currency":"GBP","odds-type":"DECIMAL","odds":400.00000,"decimal-odds":400.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99917,"currency":"GBP","odds-type":"DECIMAL","odds":170.00000,"decimal-odds":170.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":21.00000,"currency":"GBP","odds-type":"DECIMAL","odds":85.00000,"decimal-odds":85.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":1.99908,"currency":"GBP","odds-type":"DECIMAL","odds":1000.00000,"decimal-odds":1000.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:11:15.852Z","event-id":31440780971800058,"id":31440783308900058,"market-id":31440783308500058,"name":"John Parry","status":"open","volume":22567.43279,"event-participant-id":31440780978600058},{"withdrawn":false,"prices":[{"available-amount":1.99908,"currency":"GBP","odds-type":"DECIMAL","odds":28.00000,"decimal-odds":28.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":40.00000,"currency":"GBP","odds-type":"DECIMAL","odds":24.00000,"decimal-odds":24.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":16.99213,"currency":"GBP","odds-type":"DECIMAL","odds":23.00000,"decimal-odds":23.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":6.98515,"currency":"GBP","odds-type":"DECIMAL","odds":29.00000,"decimal-odds":29.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":4.99768,"currency":"GBP","odds-type":"DECIMAL","odds":30.00000,"decimal-odds":30.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":12.99398,"currency":"GBP","odds-type":"DECIMAL","odds":36.00000,"decimal-odds":36.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:17:35.952Z","event-id":31440780971800058,"id":31440783312300058,"market-id":31440783308500058,"name":"Michael Kim","status":"open","volume":21380.56539,"event-participant-id":31440780981600058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":100.00000,"decimal-odds":100.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":1.99705,"currency":"GBP","odds-type":"DECIMAL","odds":95.00000,"decimal-odds":95.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99815,"currency":"GBP","odds-type":"DECIMAL","odds":70.00000,"decimal-odds":70.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99607,"currency":"GBP","odds-type":"DECIMAL","odds":330.00000,"decimal-odds":330.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:14:48.686Z","event-id":31440780971800058,"id":31440783329801058,"market-id":31440783308500058,"name":"Andy Sullivan","status":"open","volume":17050.85155,"event-participant-id":31440780991101058},{"withdrawn":false,"prices":[{"available-amount":5.99722,"currency":"GBP","odds-type":"DECIMAL","odds":75.00000,"decimal-odds":75.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99815,"currency":"GBP","odds-type":"DECIMAL","odds":70.00000,"decimal-odds":70.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99815,"currency":"GBP","odds-type":"DECIMAL","odds":65.00000,"decimal-odds":65.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":1.99945,"currency":"GBP","odds-type":"DECIMAL","odds":120.00000,"decimal-odds":120.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":5.99116,"currency":"GBP","odds-type":"DECIMAL","odds":150.00000,"decimal-odds":150.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":3.99815,"currency":"GBP","odds-type":"DECIMAL","odds":290.00000,"decimal-odds":290.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:56:17.649Z","event-id":31440780971800058,"id":31440783312901058,"market-id":31440783308500058,"name":"Adrien Saddier","status":"open","volume":26893.09302,"event-participant-id":31440780982001058},{"withdrawn":false,"prices":[{"available-amount":1.99908,"currency":"GBP","odds-type":"DECIMAL","odds":80.00000,"decimal-odds":80.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":1.99963,"currency":"GBP","odds-type":"DECIMAL","odds":70.00000,"decimal-odds":70.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.99768,"currency":"GBP","odds-type":"DECIMAL","odds":65.00000,"decimal-odds":65.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99364,"currency":"GBP","odds-type":"DECIMAL","odds":85.00000,"decimal-odds":85.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:45:49.033Z","event-id":31440780971800058,"id":31440783323601058,"market-id":31440783308500058,"name":"Anirban Lahiri","status":"open","volume":26870.29681,"event-participant-id":31440780986201058},{"withdrawn":false,"prices":[{"available-amount":2.00000,"currency":"GBP","odds-type":"DECIMAL","odds":30.00000,"decimal-odds":30.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99411,"currency":"GBP","odds-type":"DECIMAL","odds":28.00000,"decimal-odds":28.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":6.00000,"currency":"GBP","odds-type":"DECIMAL","odds":27.00000,"decimal-odds":27.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99862,"currency":"GBP","odds-type":"DECIMAL","odds":50.00000,"decimal-odds":50.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":5.99722,"currency":"GBP","odds-type":"DECIMAL","odds":55.00000,"decimal-odds":55.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":3.99889,"currency":"GBP","odds-type":"DECIMAL","odds":90.00000,"decimal-odds":90.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:17:33.946Z","event-id":31440780971800058,"id":31440783332300058,"market-id":31440783308500058,"name":"Joost Luiten","status":"open","volume":29873.31863,"event-participant-id":31440780992801058},{"withdrawn":false,"prices":[{"available-amount":6.99676,"currency":"GBP","odds-type":"DECIMAL","odds":60.00000,"decimal-odds":60.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":3.99815,"currency":"GBP","odds-type":"DECIMAL","odds":55.00000,"decimal-odds":55.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":9.99538,"currency":"GBP","odds-type":"DECIMAL","odds":50.00000,"decimal-odds":50.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":5.99834,"currency":"GBP","odds-type":"DECIMAL","odds":180.00000,"decimal-odds":180.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":1.99945,"currency":"GBP","odds-type":"DECIMAL","odds":200.00000,"decimal-odds":200.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":3.99889,"currency":"GBP","odds-type":"DECIMAL","odds":250.00000,"decimal-odds":250.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T11:44:13.099Z","event-id":31440780971800058,"id":31440783312500058,"market-id":31440783308500058,"name":"Thriston Lawrence","status":"open","volume":25045.24829,"event-participant-id":31440780981701058},{"withdrawn":false,"prices":[{"available-amount":1.99945,"currency":"GBP","odds-type":"DECIMAL","odds":100.00000,"decimal-odds":100.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":1.99945,"currency":"GBP","odds-type":"DECIMAL","odds":95.00000,"decimal-odds":95.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":4.99861,"currency":"GBP","odds-type":"DECIMAL","odds":90.00000,"decimal-odds":90.00000,"side":"back","exchange-type":"back-lay"},{"available-amount":2.99945,"currency":"GBP","odds-type":"DECIMAL","odds":250.00000,"decimal-odds":250.00000,"side":"lay","exchange-type":"back-lay"},{"available-amount":1.99705,"currency":"GBP","odds-type":"DECIMAL","odds":290.00000,"decimal-odds":290.00000,"side":"lay","exchange-type":"back-lay"}],"last-price-update-time":"2025-10-16T12:10:11.521Z","event-id":31440780971800058,"id":31440783316201058,"market-id":31440783308500058,"name":"Darius van Driel","status":"open","volume":29270.6359,"event-participant-id":31440780984401058},{"withdrawn":false,"prices"

In [56]:
response.json()

{'runners': [{'withdrawn': False,
   'prices': [{'available-amount': 19.99075,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 7.6,
     'decimal-odds': 7.6,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 36.98288,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 7.2,
     'decimal-odds': 7.2,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 35.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 7.0,
     'decimal-odds': 7.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.99862,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.0,
     'decimal-odds': 8.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 15.9926,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.2,
     'decimal-odds': 8.2,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 18.99121,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.6,
     'decimal-odds': 8.6,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:16:42.633Z',
   'event-id': 31440780971800058,
   'id': 31440783311601058,
   'market-id': 31440783308500058,
   'name': 'Tommy Fleetwood',
   'status': 'open',
   'volume': 36405.77748,
   'event-participant-id': 31440780981101058},
  {'withdrawn': False,
   'prices': [{'available-amount': 6.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.8,
     'decimal-odds': 8.8,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 81.96206,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.6,
     'decimal-odds': 8.6,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 42.98011,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 8.4,
     'decimal-odds': 8.4,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 15.99558,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 9.0,
     'decimal-odds': 9.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 47.97779,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 9.2,
     'decimal-odds': 9.2,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 11.99445,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 9.8,
     'decimal-odds': 9.8,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:10:46.709Z',
   'event-id': 31440780971800058,
   'id': 31440783311401058,
   'market-id': 31440783308500058,
   'name': 'Rory McIlroy',
   'status': 'open',
   'volume': 37917.71295,
   'event-participant-id': 31440780981000058},
  {'withdrawn': False,
   'prices': [{'available-amount': 3.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 11.5,
     'decimal-odds': 11.5,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 5.99722,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 11.0,
     'decimal-odds': 11.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 21.98982,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 10.5,
     'decimal-odds': 10.5,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 12.0,
     'decimal-odds': 12.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 32.98473,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 12.5,
     'decimal-odds': 12.5,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 17.99167,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 13.0,
     'decimal-odds': 13.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:17:35.956Z',
   'event-id': 31440780971800058,
   'id': 31440783309101058,
   'market-id': 31440783308500058,
   'name': 'Keita Nakajima',
   'status': 'open',
   'volume': 138723.04474,
   'event-participant-id': 31440780979000058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 17.5,
     'decimal-odds': 17.5,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 21.98982,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 16.5,
     'decimal-odds': 16.5,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 22.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 16.0,
     'decimal-odds': 16.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 6.99676,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 18.0,
     'decimal-odds': 18.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 25.98797,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 19.5,
     'decimal-odds': 19.5,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 12.9964,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 20.0,
     'decimal-odds': 20.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:17:33.749Z',
   'event-id': 31440780971800058,
   'id': 31440783309501058,
   'market-id': 31440783308500058,
   'name': 'Brian Harman',
   'status': 'open',
   'volume': 18499.42904,
   'event-participant-id': 31440780979500058},
  {'withdrawn': False,
   'prices': [{'available-amount': 108.94957,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 11.0,
     'decimal-odds': 11.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 108.94957,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 10.5,
     'decimal-odds': 10.5,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 56.97362,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 9.8,
     'decimal-odds': 9.8,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 12.0,
     'decimal-odds': 12.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 18.99121,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 12.5,
     'decimal-odds': 12.5,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 45.97872,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 13.0,
     'decimal-odds': 13.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:16:33.212Z',
   'event-id': 31440780971800058,
   'id': 31440783309301058,
   'market-id': 31440783308500058,
   'name': 'Ben Griffin',
   'status': 'open',
   'volume': 16288.17449,
   'event-participant-id': 31440780979202058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.99862,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 34.0,
     'decimal-odds': 34.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 12.99398,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 32.0,
     'decimal-odds': 32.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 7.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 28.0,
     'decimal-odds': 28.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.99815,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 38.0,
     'decimal-odds': 38.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 1.99738,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 40.0,
     'decimal-odds': 40.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.99768,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 48.0,
     'decimal-odds': 48.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:16:54.709Z',
   'event-id': 31440780971800058,
   'id': 31440783312100058,
   'market-id': 31440783308500058,
   'name': 'Viktor Hovland',
   'status': 'open',
   'volume': 40491.69416,
   'event-participant-id': 31440780981401058},
  {'withdrawn': False,
   'prices': [{'available-amount': 60.97178,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.5,
     'decimal-odds': 4.5,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 52.97548,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.4,
     'decimal-odds': 4.4,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 262.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.3,
     'decimal-odds': 4.3,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 61.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.6,
     'decimal-odds': 4.6,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 261.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.7,
     'decimal-odds': 4.7,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 237.88988,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 4.8,
     'decimal-odds': 4.8,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:15:25.287Z',
   'event-id': 31440780971800058,
   'id': 31440783311900058,
   'market-id': 31440783308500058,
   'name': 'Shane Lowry',
   'status': 'open',
   'volume': 15927.96255,
   'event-participant-id': 31440780981201058},
  {'withdrawn': False,
   'prices': [{'available-amount': 1.99945,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 130.0,
     'decimal-odds': 130.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 1.99945,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 120.0,
     'decimal-odds': 120.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.99411,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 110.0,
     'decimal-odds': 110.0,
     'side': 'back',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:02:30.134Z',
   'event-id': 31440780971800058,
   'id': 31440783309701058,
   'market-id': 31440783308500058,
   'name': 'Angel Ayora',
   'status': 'open',
   'volume': 21857.74742,
   'event-participant-id': 31440780979601058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 38.0,
     'decimal-odds': 38.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 36.0,
     'decimal-odds': 36.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 18.972,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 32.0,
     'decimal-odds': 32.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 7.98821,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 80.0,
     'decimal-odds': 80.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 8.99835,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 110.0,
     'decimal-odds': 110.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 350.0,
     'decimal-odds': 350.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:17:37.583Z',
   'event-id': 31440780971800058,
   'id': 31440783322300058,
   'market-id': 31440783308500058,
   'name': 'Jorge Campillo',
   'status': 'open',
   'volume': 22577.81367,
   'event-participant-id': 31440780985301058},
  {'withdrawn': False,
   'prices': [{'available-amount': 1.99908,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 85.0,
     'decimal-odds': 85.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.99815,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 80.0,
     'decimal-odds': 80.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.99945,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 75.0,
     'decimal-odds': 75.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.99425,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 180.0,
     'decimal-odds': 180.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:52:21.168Z',
   'event-id': 31440780971800058,
   'id': 31440783328201058,
   'market-id': 31440783308500058,
   'name': 'Jordan Smith',
   'status': 'open',
   'volume': 30405.47223,
   'event-participant-id': 31440780989901058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 60.0,
     'decimal-odds': 60.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 55.0,
     'decimal-odds': 55.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 11.99668,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 46.0,
     'decimal-odds': 46.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 13.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 85.0,
     'decimal-odds': 85.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:10:11.521Z',
   'event-id': 31440780971800058,
   'id': 31440783331100058,
   'market-id': 31440783308500058,
   'name': 'Jayden Trey Schaper',
   'status': 'open',
   'volume': 28125.67307,
   'event-participant-id': 31440780992000058},
  {'withdrawn': False,
   'prices': [{'available-amount': 4.99768,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 400.0,
     'decimal-odds': 400.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.99917,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 170.0,
     'decimal-odds': 170.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 21.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 85.0,
     'decimal-odds': 85.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 1.99908,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 1000.0,
     'decimal-odds': 1000.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:11:15.852Z',
   'event-id': 31440780971800058,
   'id': 31440783308900058,
   'market-id': 31440783308500058,
   'name': 'John Parry',
   'status': 'open',
   'volume': 22567.43279,
   'event-participant-id': 31440780978600058},
  {'withdrawn': False,
   'prices': [{'available-amount': 1.99908,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 28.0,
     'decimal-odds': 28.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 40.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 24.0,
     'decimal-odds': 24.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 16.99213,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 23.0,
     'decimal-odds': 23.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 6.98515,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 29.0,
     'decimal-odds': 29.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.99768,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 30.0,
     'decimal-odds': 30.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 12.99398,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 36.0,
     'decimal-odds': 36.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:17:35.952Z',
   'event-id': 31440780971800058,
   'id': 31440783312300058,
   'market-id': 31440783308500058,
   'name': 'Michael Kim',
   'status': 'open',
   'volume': 21380.56539,
   'event-participant-id': 31440780981600058},
  {'withdrawn': False,
   'prices': [{'available-amount': 2.0,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 100.0,
     'decimal-odds': 100.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 1.99705,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 95.0,
     'decimal-odds': 95.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.99815,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 70.0,
     'decimal-odds': 70.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 2.99607,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 330.0,
     'decimal-odds': 330.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T12:14:48.686Z',
   'event-id': 31440780971800058,
   'id': 31440783329801058,
   'market-id': 31440783308500058,
   'name': 'Andy Sullivan',
   'status': 'open',
   'volume': 17050.85155,
   'event-participant-id': 31440780991101058},
  {'withdrawn': False,
   'prices': [{'available-amount': 5.99722,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 75.0,
     'decimal-odds': 75.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.99815,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 70.0,
     'decimal-odds': 70.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.99815,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 65.0,
     'decimal-odds': 65.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 1.99945,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 120.0,
     'decimal-odds': 120.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 5.99116,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 150.0,
     'decimal-odds': 150.0,
     'side': 'lay',
     'exchange-type': 'back-lay'},
    {'available-amount': 3.99815,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 290.0,
     'decimal-odds': 290.0,
     'side': 'lay',
     'exchange-type': 'back-lay'}],
   'last-price-update-time': '2025-10-16T11:56:17.649Z',
   'event-id': 31440780971800058,
   'id': 31440783312901058,
   'market-id': 31440783308500058,
   'name': 'Adrien Saddier',
   'status': 'open',
   'volume': 26893.09302,
   'event-participant-id': 31440780982001058},
  {'withdrawn': False,
   'prices': [{'available-amount': 1.99908,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 80.0,
     'decimal-odds': 80.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 1.99963,
     'currency': 'GBP',
     'odds-type': 'DECIMAL',
     'odds': 70.0,
     'decimal-odds': 70.0,
     'side': 'back',
     'exchange-type': 'back-lay'},
    {'available-amount': 4.99768,
     'currency': 'GBP',

In [58]:
# place a bet
# lump tommy fleetwood

url = "https://api.matchbook.com/edge/rest/v2/offers"

headers = {
    "accept": "application/json",
    'session-token': '681420_fd6b6c96b3e6dfedf0e82de77454c923',
    "content-type": "application/json"
}

runner_id = 31440783311601058 # id in the above
side = 'back' # can be back, lay, win, lose
stake = 1
odds = 7.8

params = {
    'offers': [{'runner-id': runner_id, 'side': side, 'stake': float(stake), 'odds': float(odds)}],
    # 'odds-type': self.client.odds_type,  default DECIMAL
    # 'exchange-type': self.client.exchange_type, default back-lay
    # 'currency': self.client.currency, not required
}

response = requests.post(url, data=json.dumps(params), headers=headers)
print(response.text)

{"language":"en","currency":"GBP","exchange-type":"back-lay","odds-type":"DECIMAL","offers":[{"id":31466113667700024,"event-id":31440780971800058,"event-name":"DP World India Championship 2025 ","market-id":31440783308500058,"market-name":"Winner","market-type":"outright","product":"EXCHANGE","runner-id":31440783311601058,"runner-name":"Tommy Fleetwood","sport-id":8,"exchange-type":"back-lay","side":"back","odds":7.80000,"odds-type":"DECIMAL","decimal-odds":7.80000,"stake":1.0,"remaining":1.0,"potential-profit":6.80000,"remaining-potential-profit":6.80000,"commission-type":"VOLUME","originator-commission-rate":0.0,"acceptor-commission-rate":0.0,"commission-reserve":0.0,"currency":"GBP","created-at":"2025-10-16T12:33:28.107Z","last-modified-time":"2025-10-16T12:33:28.107Z","status":"open","in-play":true,"keep-in-play":false,"use-bonus":false}]}

In [59]:
# check my positions
# can pass through specific event, market or runner

url = "https://api.matchbook.com/edge/rest/account/positions?per-page=200"

headers = {
    "accept": "application/json",
    'session-token': '681420_fd6b6c96b3e6dfedf0e82de77454c923',
}

response = requests.get(url, headers=headers)
print(response.text)

{"positions":[{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783308900058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783309101058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783309301058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783309501058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783309701058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783309901058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783310400058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783310601058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783310801058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783311001058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783311201058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783311401058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783311601058,"potential-profit":6.79993},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783311900058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783312100058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783312300058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783312500058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783312701058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783312901058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783313101058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783313301058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783313501058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783313701058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783314000058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783314200058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783314400058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783314600058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783314800058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783315000058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783315401058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783315601058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783315801058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783316001058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783316201058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783316401058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783316601058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783316801058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783317100058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783322100058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783322300058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783322501058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783322800058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783323000058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783323200058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783323401058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783323601058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783323900058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783324100058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783324300058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783324500058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783324700058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783324901058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783325101058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783325301058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783325501058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783325701058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783325901058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783326101058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783326301058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783326600058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783326800058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783327000058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783327200058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783327401058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783327601058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783327801058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783328001058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783328201058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783328401058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783328601058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783328801058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783329001058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783329201058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783329401058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783329601058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783329801058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783330001058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783330201058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783330401058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783330601058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783330801058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783331100058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783331300058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783331500058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783331601058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783331900058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783332100058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783332300058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783332500058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783332700058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783332900058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783333100058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783333300058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783333500058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783333700058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783333900058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783334100058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783334301058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783334501058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783334701058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783334901058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783335101058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783335301058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783335501058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783335701058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783335901058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783336101058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783336301058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783336501058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783336701058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783337000058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783337201058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783337401058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783337601058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783337801058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783338100058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783338300058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783338500058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783338701058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783338901058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783339100058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783339300058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783339501058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783339701058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783339901058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783340101058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783340301058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31440783340501058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31441030929101058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31441045152501058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31441049508700058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31441054763202058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31441059119900058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31441065322202058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31441069433300058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31441074678802058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31447586279900058,"potential-loss":-0.99999},{"event-id":31440780971800058,"market-id":31440783308500058,"runner-id":31448477050200058,"potential-loss":-0.99999}],"offset":0,"total":138,"per-page":200}

In [63]:
pd.DataFrame(response.json()['positions']).sort_values(by='potential-profit')

,event-id,market-id,runner-id,potential-loss,potential-profit
12,31440780971800058,31440783308500058,31440783311601058,NaN,6.79993
0,31440780971800058,31440783308500058,31440783308900058,-0.99999,NaN
1,31440780971800058,31440783308500058,31440783309101058,-0.99999,NaN
2,31440780971800058,31440783308500058,31440783309301058,-0.99999,NaN
3,31440780971800058,31440783308500058,31440783309501058,-0.99999,NaN
...,...,...,...,...,...
133,31440780971800058,31440783308500058,31441065322202058,-0.99999,NaN
134,31440780971800058,31440783308500058,31441069433300058,-0.99999,NaN
135,31440780971800058,31440783308500058,31441074678802058,-0.99999,NaN
136,31440780971800058,31440783308500058,31447586279900058,-0.99999,NaN
137,31440780971800058,31440783308500058,31448477050200058,-0.99999,NaN

In [64]:
# logout

url = "https://api.matchbook.com/bpapi/rest/security/session"

headers = {
    "accept": "application/json",
    'session-token': '681420_fd6b6c96b3e6dfedf0e82de77454c923'
    #"User-Agent": "api-doc-test-client"
}

response = requests.delete(url, headers=headers)

print(response.text)

{"session-token":"681420_fd6b6c96b3e6dfedf0e82de77454c923","user-id":681420,"username":"adbushnell"}